### 添加图片元数据信息
POST http://localhost:1417/metadata/addMetadata HTTP/1.1
Content-Type: application/json

{
  "photoId": 50
}

### 更新图片元数据信息
POST http://localhost:1417/metadata/update/4 HTTP/1.1
Content-Type: application/json

{
  "photoId": 53
}

### 查询图片信息
GET http://localhost:1417/metadata/list HTTP/1.1